# Generated by Django 5.0.7 on 2024-07-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='문서명')),
                ('key_values', models.JSONField(blank=True, default=dict, null=True, verbose_name='키-밸류')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일자')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
            ],
        ),
    ]
