# Generated by Django 5.0.7 on 2024-07-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TsExpert', '0002_alter_keyvalue_key_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyvalue',
            name='key_values',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='키-밸류'),
        ),
    ]
