# Generated by Django 5.0.7 on 2024-07-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TsExpert', '0004_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='fee',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='수수료'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_payment_period',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='이자상환기한'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='irr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IRR'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='joint_guarantee_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='연대보증금액'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='당사여신금액'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_period',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='대출기간'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='overdue_interest_rate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='연체이자율'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='prepayment_fee',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='중도상환수수료'),
        ),
    ]
