# Generated by Django 5.0.7 on 2024-07-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TsExpert', '0005_alter_loan_fee_alter_loan_interest_payment_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_table', models.BooleanField(default=False)),
                ('synonym_priority', models.CharField(blank=True, max_length=255, null=True)),
                ('synonym_all', models.CharField(blank=True, max_length=255, null=True)),
                ('synonym_pattern', models.TextField(blank=True, null=True)),
                ('specific', models.BooleanField(default=False)),
                ('sp_word', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('split', models.TextField(blank=True, null=True)),
                ('map_key', models.CharField(blank=True, max_length=255, null=True)),
                ('map_value', models.CharField(blank=True, max_length=255, null=True)),
                ('in_use', models.BooleanField(default=True)),
            ],
        ),
    ]
