# Generated by Django 5.0.7 on 2024-07-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TsExpert', '0006_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='specific',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='synonym_priority',
        ),
        migrations.AlterField(
            model_name='metadata',
            name='synonym_all',
            field=models.CharField(blank=True, default='[]', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='synonym_pattern',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
