# Generated by Django 5.0.7 on 2024-07-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TsExpert', '0007_remove_metadata_specific_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='map_key',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='map_value',
        ),
        migrations.AddField(
            model_name='metadata',
            name='map',
            field=models.CharField(blank=True, default='{}', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='split',
            field=models.CharField(blank=True, default='[]', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='value',
            field=models.CharField(blank=True, default='[]', max_length=255, null=True),
        ),
    ]
