# Generated by Django 5.0.7 on 2024-07-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TsExpert', '0009_alter_metadata_is_table_alter_metadata_synonym_all_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='type',
            field=models.CharField(blank=True, choices=[('string', 'String'), ('name', 'Name'), ('department', 'Department'), ('year', 'Year'), ('number', 'Number'), ('date', 'Date'), ('money', 'Money'), ('percentage', 'Percentage'), ('map', 'Map'), ('company', 'Company')], max_length=50, null=True),
        ),
    ]
