# Generated by Django 5.0.7 on 2024-07-31 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TsExpert', '0011_alter_metadata_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='파일명')),
                ('contract_type', models.CharField(choices=[('투자신청의견서', '투자신청의견서'), ('신탁계약서', '신탁계약서'), ('전담중개업무계약서', '전담중개업무계약서')], default='신탁계약서', max_length=32, verbose_name='계약서 종류')),
                ('content', models.FileField(upload_to='documents/templates', verbose_name='파일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='Edited At')),
                ('idx_pos', models.JSONField(blank=True, default=list, null=True, verbose_name='인덱스 위치')),
            ],
            options={
                'verbose_name': '템플릿 (template)',
                'verbose_name_plural': '템플릿 (template)',
                'db_table': 'template',
            },
        ),
    ]
