# Generated by Django 5.0.7 on 2024-07-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TsExpert', '0013_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='final_text',
            field=models.TextField(blank=True, null=True, verbose_name='결과텍스트'),
        ),
        migrations.AddField(
            model_name='rules',
            name='highlight',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='하이라이트 여부'),
        ),
        migrations.AddField(
            model_name='rules',
            name='template_idx',
            field=models.IntegerField(default=0, verbose_name='템플릿위치 인덱스'),
        ),
        migrations.AddField(
            model_name='rules',
            name='상환후불여부',
            field=models.CharField(blank=True, choices=[('후불', '후불'), ('선불', '선불')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rules',
            name='원금상환여부',
            field=models.CharField(blank=True, choices=[('균등분할상환', '균등분할상환'), ('만기일시상환', '만기일시상환')], max_length=30, null=True),
        ),
    ]
