# Generated by Django 5.0.7 on 2024-07-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TsExpert', '0014_rules_final_text_rules_highlight_rules_template_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rules',
            name='상환후불여부',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='원금상환여부',
        ),
        migrations.AddField(
            model_name='rules',
            name='deferred_payment',
            field=models.CharField(blank=True, choices=[('후불', '후불'), ('선불', '선불')], max_length=30, null=True, verbose_name='상환후불여부'),
        ),
        migrations.AddField(
            model_name='rules',
            name='principal_repayment_type',
            field=models.CharField(blank=True, choices=[('균등분할상환', '균등분할상환'), ('만기일시상환', '만기일시상환')], max_length=30, null=True, verbose_name='원금상환여부'),
        ),
    ]
