# Generated by Django 5.0.7 on 2024-08-02 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TsExpert', '0015_remove_rules_상환후불여부_remove_rules_원금상환여부_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name': 'Job 로그', 'verbose_name_plural': 'Job 로그'},
        ),
        migrations.AlterModelOptions(
            name='metadata',
            options={'verbose_name': '사전', 'verbose_name_plural': '사전'},
        ),
        migrations.AlterModelOptions(
            name='rules',
            options={'verbose_name': '조건정의', 'verbose_name_plural': '조건정의'},
        ),
    ]
