# Generated by Django 5.0.7 on 2024-08-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TsExpert', '0017_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='extract_all_json',
            field=models.BooleanField(default=False),
        ),
    ]
