# Generated by Django 5.0.7 on 2024-09-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TsExpert', '0018_metadata_extract_all_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, choices=[('string', 'String'), ('name', 'Name'), ('department', 'Department'), ('year', 'Year'), ('number', 'Number'), ('date', 'Date'), ('money', 'Money'), ('percentage', 'Percentage'), ('map', 'Map'), ('company', 'Company')], default='string', max_length=50, null=True)),
                ('is_table', models.BooleanField(default=True)),
                ('extract_all_json', models.BooleanField(default=False)),
                ('synonym_all', models.CharField(blank=True, default='[]', max_length=600, null=True)),
                ('synonym_pattern', models.CharField(blank=True, default='[]', max_length=255, null=True)),
                ('second_key', models.CharField(blank=True, default='[]', max_length=600, null=True)),
                ('sp_word', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, default='[]', max_length=255, null=True)),
                ('split', models.CharField(blank=True, default='[]', max_length=255, null=True)),
                ('map', models.CharField(blank=True, default='{}', max_length=255, null=True)),
                ('in_use', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '사전',
                'verbose_name_plural': '사전',
            },
        ),
        migrations.DeleteModel(
            name='MetaData',
        ),
    ]
