# Generated by Django 5.0.7 on 2024-09-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TsExpert', '0019_dictionary_delete_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='second_key',
        ),
        migrations.AddField(
            model_name='dictionary',
            name='extract_second_key',
            field=models.BooleanField(default=False),
        ),
    ]
