# Generated by Django 5.1.2 on 2024-10-17 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TsExpert', '0021_remove_dictionary_extract_second_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='아이디')),
                ('type_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='타입명')),
                ('type_name_kor', models.CharField(blank=True, max_length=255, null=True, verbose_name='한국어 타입명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일자')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
            ],
            options={
                'verbose_name': '문서타입',
                'verbose_name_plural': '문서타입',
            },
        ),
        migrations.CreateModel(
            name='ExtractDictionary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='아이디')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='사용처명')),
                ('user', models.CharField(blank=True, max_length=255, null=True, verbose_name='유저')),
                ('dictionary', models.JSONField(blank=True, default=list, null=True, verbose_name='딕셔너리')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일자')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
                ('in_use', models.BooleanField(default=True, verbose_name='사용여부')),
            ],
            options={
                'verbose_name': '사전',
                'verbose_name_plural': '사전',
            },
        ),
        migrations.CreateModel(
            name='PrimaryExtractedValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=255, verbose_name='문서 이름')),
                ('key', models.CharField(max_length=255, verbose_name='추출키')),
                ('value_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('table', 'Table'), ('image&table', 'Image&Table'), ('any', 'Any')], default='text', max_length=50, verbose_name='추출값 형식')),
                ('text_value', models.TextField(blank=True, null=True, verbose_name='텍스트 추출값')),
                ('image_value', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='이미지 추출값')),
                ('table_value', models.TextField(blank=True, null=True, verbose_name='테이블 추출값(XML)')),
                ('table_value_images', models.ImageField(blank=True, null=True, upload_to='tables/', verbose_name='테이블 추출값(이미지)')),
                ('user', models.CharField(max_length=255, verbose_name='유저')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일자')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TsExpert.documenttype', verbose_name='문서 유형')),
            ],
            options={
                'verbose_name': '추출 키-밸류',
                'verbose_name_plural': '추출 키-밸류',
            },
        ),
    ]
