# Generated by Django 5.1.2 on 2024-10-17 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TsExpert', '0022_documenttype_extractdictionary_primaryextractedvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractdictionary',
            name='document_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TsExpert.documenttype', verbose_name='문서 유형'),
        ),
    ]
