# Generated by Django 5.1.2 on 2024-10-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TsExpert', '0024_imextraction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
    ]
