# Generated by Django 5.1.2 on 2024-10-18 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TsExpert', '0025_delete_template'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dictionary',
        ),
        migrations.DeleteModel(
            name='KeyValue',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.DeleteModel(
            name='Rules',
        ),
    ]
