# Generated by Django 5.1.2 on 2024-10-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TsExpert', '0026_delete_dictionary_delete_keyvalue_delete_loan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imextraction',
            name='dev_plan',
            field=models.TextField(blank=True, null=True, verbose_name='사업부지개발계획'),
        ),
        migrations.AddField(
            model_name='imextraction',
            name='fund_execution',
            field=models.TextField(blank=True, null=True, verbose_name='자금조달및집행'),
        ),
        migrations.AddField(
            model_name='imextraction',
            name='procure_amount',
            field=models.TextField(blank=True, null=True, verbose_name='조달금액'),
        ),
    ]
