# Generated by Django 5.1.2 on 2024-10-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocGenerator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('template_idx', models.IntegerField(default=0, verbose_name='템플릿위치 인덱스')),
                ('final_text', models.TextField(blank=True, null=True, verbose_name='결과텍스트')),
                ('highlight', models.BooleanField(blank=True, default=False, null=True, verbose_name='하이라이트 여부')),
                ('deferred_payment', models.CharField(blank=True, choices=[('후불', '후불'), ('선불', '선불')], max_length=30, null=True, verbose_name='상환후불여부')),
                ('principal_repayment_type', models.CharField(blank=True, choices=[('균등분할상환', '균등분할상환'), ('만기일시상환', '만기일시상환')], max_length=30, null=True, verbose_name='원금상환여부')),
            ],
            options={
                'verbose_name': '조건정의',
                'verbose_name_plural': '조건정의',
            },
        ),
    ]
