# Generated by Django 5.0.7 on 2024-07-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TsExpert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyvalue',
            name='key_values',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='키-밸류'),
        ),
    ]
